### ISSUE TITLE
Default install within conda does not work

### ISSUE THREAD

**Issue by DStrelak** [scipion-em/scipion-installer#17]
**Steps to reproduce**
```
$ pip list
Package                Version            
---------------------- -------------------
...     
scipion-installer      1.0.6b4            
...  
$ python --version
Python 3.8.2
$ python3 -m scipioninstaller ~/git/scipion3
conda detected. Favouring it. If you want a virtualenv installation cancel installation and pass --venv .
Conda installations will have a poor font and may affect your user experience. Are you sure you want to continue? (y/n): y
This is an early version of the installer. So far only works for developers installing an unstable version.Are you sure you want to continue? (y/n): y
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/david/miniconda2/envs/.scipion3env

  added / updated specs:
    - python=3


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.6.24-0
  certifi            pkgs/main/linux-64::certifi-2020.6.20-py38_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h7b6447c_0
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1g-h7b6447c_0
  pip                pkgs/main/linux-64::pip-20.1.1-py38_1
  python             pkgs/main/linux-64::python-3.8.3-hcff3b4d_2
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  setuptools         pkgs/main/linux-64::setuptools-47.3.1-py38_0
  sqlite             pkgs/main/linux-64::sqlite-3.32.3-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py38_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate .scipion3env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting scipion-pyworkflow
  Downloading scipion-pyworkflow-3.0.0.tar.gz (1.0 MB)
     |████████████████████████████████| 1.0 MB 728 kB/s 
Collecting numpy
  Using cached numpy-1.19.0-cp38-cp38-manylinux2010_x86_64.whl (14.6 MB)
Processing /home/david/.cache/pip/wheels/90/c9/b6/04665702b01dbd9ee92a05e834b627948ed01cdd482e6a78e1/psutil-5.7.0-cp38-cp38-linux_x86_64.whl
Collecting matplotlib
  Using cached matplotlib-3.2.2-cp38-cp38-manylinux1_x86_64.whl (12.4 MB)
Collecting pillow
  Using cached Pillow-7.2.0-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
Processing /home/david/.cache/pip/wheels/9a/bf/37/abf100a7ad8c8bb49b300653a358ee67f195dfc471a1b56e4c/bibtexparser-1.2.0-py3-none-any.whl
Collecting requests
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting configparser
  Using cached configparser-5.0.0-py3-none-any.whl (22 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp38-cp38-manylinux1_x86_64.whl (92 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Processing /home/david/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4/future-0.18.2-py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: certifi>=2017.4.17 in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from requests->scipion-pyworkflow) (2020.6.20)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: scipion-pyworkflow
  Building wheel for scipion-pyworkflow (setup.py) ... done
  Created wheel for scipion-pyworkflow: filename=scipion_pyworkflow-3.0.0-py3-none-any.whl size=832903 sha256=444cfd2c8219fc09e1ededd93146e0fd129944ef751ecafe1ae05fc213792827
  Stored in directory: /home/david/.cache/pip/wheels/9f/ad/7a/8c728f920e80fb2c724e0ca1f0e26386fa96e90c0d224bc899
Successfully built scipion-pyworkflow
Installing collected packages: numpy, psutil, kiwisolver, six, cycler, python-dateutil, pyparsing, matplotlib, pillow, future, bibtexparser, urllib3, chardet, idna, requests, configparser, scipion-pyworkflow
Successfully installed bibtexparser-1.2.0 chardet-3.0.4 configparser-5.0.0 cycler-0.10.0 future-0.18.2 idna-2.10 kiwisolver-1.2.0 matplotlib-3.2.2 numpy-1.19.0 pillow-7.2.0 psutil-5.7.0 pyparsing-2.4.7 python-dateutil-2.8.1 requests-2.24.0 scipion-pyworkflow-3.0.0 six-1.15.0 urllib3-1.25.9
Collecting scipion-app
  Downloading scipion-app-3.0.1b3.tar.gz (71 kB)
     |████████████████████████████████| 71 kB 208 kB/s 
Collecting scipion-em
  Downloading scipion_em-3.0.1b3-py3-none-any.whl (380 kB)
     |████████████████████████████████| 380 kB 1.9 MB/s 
Collecting outdated==0.2.0
  Downloading outdated-0.2.0.tar.gz (4.0 kB)
Requirement already satisfied: scipion-pyworkflow in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from scipion-em->scipion-app) (3.0.0)
Collecting biopython==1.76
  Using cached biopython-1.76-cp38-cp38-manylinux1_x86_64.whl (2.3 MB)
Collecting littleutils
  Downloading littleutils-0.2.2.tar.gz (6.6 kB)
Requirement already satisfied: requests in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from outdated==0.2.0->scipion-app) (2.24.0)
Requirement already satisfied: psutil in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-app) (5.7.0)
Requirement already satisfied: bibtexparser in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-app) (1.2.0)
Requirement already satisfied: numpy in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-app) (1.19.0)
Requirement already satisfied: configparser in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-app) (5.0.0)
Requirement already satisfied: matplotlib in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-app) (3.2.2)
Requirement already satisfied: pillow in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-app) (7.2.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from requests->outdated==0.2.0->scipion-app) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from requests->outdated==0.2.0->scipion-app) (1.25.9)
Requirement already satisfied: idna<3,>=2.5 in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from requests->outdated==0.2.0->scipion-app) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from requests->outdated==0.2.0->scipion-app) (2020.6.20)
Requirement already satisfied: future>=0.16.0 in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from bibtexparser->scipion-pyworkflow->scipion-em->scipion-app) (0.18.2)
Requirement already satisfied: pyparsing>=2.0.3 in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from bibtexparser->scipion-pyworkflow->scipion-em->scipion-app) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from matplotlib->scipion-pyworkflow->scipion-em->scipion-app) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from matplotlib->scipion-pyworkflow->scipion-em->scipion-app) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from matplotlib->scipion-pyworkflow->scipion-em->scipion-app) (2.8.1)
Requirement already satisfied: six in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from cycler>=0.10->matplotlib->scipion-pyworkflow->scipion-em->scipion-app) (1.15.0)
Building wheels for collected packages: scipion-app, outdated, littleutils
  Building wheel for scipion-app (setup.py) ... done
  Created wheel for scipion-app: filename=scipion_app-3.0.1b3-py3-none-any.whl size=84886 sha256=7caa723a14198c79bafe307e7142e74ee15f5bbc6e9060f30738e7cf9469c606
  Stored in directory: /home/david/.cache/pip/wheels/70/76/52/ce7e6a84a841ce61d7bc4f9d98035b1b01ba44211b98b56337
  Building wheel for outdated (setup.py) ... done
  Created wheel for outdated: filename=outdated-0.2.0-py3-none-any.whl size=4960 sha256=51bb22fe54125ae40ac4b82a42f1cf68a51a93a4fcdb23ec0921df5d31c4b7d6
  Stored in directory: /home/david/.cache/pip/wheels/2d/4f/c9/062da6e68841f60d0c3434980775671daaa07a574110567de6
  Building wheel for littleutils (setup.py) ... done
  Created wheel for littleutils: filename=littleutils-0.2.2-py3-none-any.whl size=7048 sha256=23e9e1316075faf59182ac224acee028535746004179b577f065f4351f511536
  Stored in directory: /home/david/.cache/pip/wheels/6a/33/c4/0ef84d7f5568c2823e3d63a6e08988852fb9e4bc822034870a
Successfully built scipion-app outdated littleutils
Installing collected packages: biopython, scipion-em, littleutils, outdated, scipion-app
Successfully installed biopython-1.76 littleutils-0.2.2 outdated-0.2.0 scipion-app-3.0.1b3 scipion-em-3.0.1b3
Scipion v3.0 () devel

Building scipion-em-xmipp ...
/home/david/miniconda2/envs/.scipion3env/bin/python -m pip install scipion-em-xmipp==20.7b1
Collecting scipion-em-xmipp==20.7b1
  Downloading scipion-em-xmipp-20.7b1.tar.gz (651 kB)
     |████████████████████████████████| 651 kB 554 kB/s 
Collecting scikit-learn==0.22.1
  Using cached scikit_learn-0.22.1-cp38-cp38-manylinux1_x86_64.whl (7.0 MB)
Collecting joblib
  Using cached joblib-0.16.0-py3-none-any.whl (300 kB)
Collecting peppercorn
  Using cached peppercorn-0.6-py3-none-any.whl (4.8 kB)
Collecting plotter
  Using cached plotter-1.3.9-py3-none-any.whl (10 kB)
Collecting scons
  Using cached SCons-4.0.0-py3-none-any.whl (4.0 MB)
Requirement already satisfied: numpy>=1.11.0 in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from scikit-learn==0.22.1->scipion-em-xmipp==20.7b1) (1.19.0)
Collecting scipy>=0.17.0
  Using cached scipy-1.5.1-cp38-cp38-manylinux1_x86_64.whl (25.8 MB)
Requirement already satisfied: setuptools in /home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages (from scons->scipion-em-xmipp==20.7b1) (47.3.1.post20200622)
Building wheels for collected packages: scipion-em-xmipp
  Building wheel for scipion-em-xmipp (setup.py) ... done
  Created wheel for scipion-em-xmipp: filename=scipion_em_xmipp-20.7b1-py3-none-any.whl size=849492 sha256=13d14f9117eaa7b44ba048a10f512742d6b052f15aa5375dbd26e2a6d27c437b
  Stored in directory: /home/david/.cache/pip/wheels/22/f0/d3/8b184e44c6aa4e988b9f8157e76c43d10dc144b38654d5531a
Successfully built scipion-em-xmipp
Installing collected packages: scipy, joblib, scikit-learn, peppercorn, plotter, scons, scipion-em-xmipp
Successfully installed joblib-0.16.0 peppercorn-0.6 plotter-1.3.9 scikit-learn-0.22.1 scipion-em-xmipp-20.7b1 scipy-1.5.1 scons-4.0.0
Done (9.36 seconds)
Building xmippSrc-3.20.07b1 ...
wget -nv -c -O /home/david/git/scipion3/software/em/xmippSrc-v3.20.07b1.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/em/xmippSrc-v3.20.07b1.tgz
http://scipion.cnb.csic.es/downloads/scipion/software/em/xmippSrc-v3.20.07b1.tgz:
2020-07-07 17:31:13 ERROR 404: Not Found.
mv -v /home/david/git/scipion3/software/em/xmippSrc-v3.20.07b1.tgz.part /home/david/git/scipion3/software/em/xmippSrc-v3.20.07b1.tgz
renamed '/home/david/git/scipion3/software/em/xmippSrc-v3.20.07b1.tgz.part' -> '/home/david/git/scipion3/software/em/xmippSrc-v3.20.07b1.tgz'
cd /home/david/git/scipion3/software/em
tar -xf xmippSrc-v3.20.07b1.tgz
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages/scipion/__main__.py", line 443, in <module>
    main()
  File "/home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages/scipion/__main__.py", line 287, in main
    installPluginMethods()
  File "/home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/install_plugin.py", line 231, in installPluginMethods
    plugin.installBin({'args': ['-j', numberProcessor]})
  File "/home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/plugin_funcs.py", line 166, in installBin
    environment.execute()
  File "/home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/funcs.py", line 748, in execute
    self._executeTargets(targetList)
  File "/home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/funcs.py", line 690, in _executeTargets
    tgt.execute()
  File "/home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/funcs.py", line 220, in execute
    command.execute()
  File "/home/david/miniconda2/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/funcs.py", line 160, in execute
    assert glob(t), ("target '%s' not built (after "
AssertionError: target '/home/david/git/scipion3/software/em/xmippSrc-v3.20.07b1' not built (after running 'tar -xf xmippSrc-v3.20.07b1.tgz')
Error at main: target '/home/david/git/scipion3/software/em/xmippSrc-v3.20.07b1' not built (after running 'tar -xf xmippSrc-v3.20.07b1.tgz')

Something went wrong running: 
 eval "$(/home/david/miniconda2/bin/conda shell.bash hook)" &&
conda create  -n .scipion3env python=3 &&
conda activate .scipion3env &&
cd /home/david/git/scipion3 &&
mkdir -p software/lib &&
mkdir -p software/bindings &&
mkdir -p software/em &&
export SCIPION_HOME=/home/david/git/scipion3 &&
pip install scipion-pyworkflow &&
pip install scipion-app &&
python -m scipion installp -p scipion-em-xmipp -j 8
Installation cancelled.
```

**Comment by azazellochg** [comment]
well, that's xmipp problem that tar doesnt exist @dmaluenda

**Comment by pconesa** [comment]
Yep this was during migration of the server. File is back: http://scipion.cnb.csic.es/downloads/scipion/software/em/xmippSrc-v3.20.07b1.tgz
