### ISSUE TITLE
Cannot remove 'xmipp_mpi_test_main*'

### ISSUE THREAD

**Issue by ammarik** [scipion-em/scipion-installer#23]
Hello,
I'm trying to install Scipion 3 on Ubuntu 20.04 and I got stuck on the following error. Can you help me please?

``` 
 mpirun or mpiexec have failed.
 Cannot compile with MPI or use it
 rm xmipp_mpi_test_main*
rm: cannot remove 'xmipp_mpi_test_main*': No such file or directory
 
Check failed! Something wrong with the configuration.

Traceback (most recent call last):
  File "/cryoem/software/scipion/scipion-3/.scipion3env/lib/python3.8/site-packages/scipion/__main__.py", line 449, in <module>
    main()
  File "/cryoem/software/scipion/scipion-3/.scipion3env/lib/python3.8/site-packages/scipion/__main__.py", line 292, in main
    installPluginMethods()
  File "/cryoem/software/scipion/scipion-3/.scipion3env/lib/python3.8/site-packages/scipion/install/install_plugin.py", line 231, in installPluginMethods
    plugin.installBin({'args': ['-j', numberProcessor]})
  File "/cryoem/software/scipion/scipion-3/.scipion3env/lib/python3.8/site-packages/scipion/install/plugin_funcs.py", line 166, in installBin
    environment.execute()
  File "/cryoem/software/scipion/scipion-3/.scipion3env/lib/python3.8/site-packages/scipion/install/funcs.py", line 748, in execute
    self._executeTargets(targetList)
  File "/cryoem/software/scipion/scipion-3/.scipion3env/lib/python3.8/site-packages/scipion/install/funcs.py", line 690, in _executeTargets
    tgt.execute()
  File "/cryoem/software/scipion/scipion-3/.scipion3env/lib/python3.8/site-packages/scipion/install/funcs.py", line 220, in execute
    command.execute()
  File "/cryoem/software/scipion/scipion-3/.scipion3env/lib/python3.8/site-packages/scipion/install/funcs.py", line 160, in execute
    assert glob(t), ("target '%s' not built (after "
AssertionError: target '/cryoem/software/scipion/scipion-3/software/em/xmipp/bin/xmipp_reconstruct_significant' not built (after running 'cd . && ./xmipp config noAsk && ./xmipp check_config && ./xmipp compileAndInstall N=8 && ln -srf build /cryoem/software/scipion/scipion-3/software/em/xmipp && cd - && touch installation_finished && rm bindings_linked 2> /dev/null')
Error at main: target '/cryoem/software/scipion/scipion-3/software/em/xmipp/bin/xmipp_reconstruct_significant' not built (after running 'cd . && ./xmipp config noAsk && ./xmipp check_config && ./xmipp compileAndInstall N=8 && ln -srf build /cryoem/software/scipion/scipion-3/software/em/xmipp && cd - && touch installation_fin
ished && rm bindings_linked 2> /dev/null')
```

Complete outpu of `python3 -m scipioninstaller ../scipion-3` command: [Log.txt](https://github.com/scipion-em/scipion-installer/files/5316754/Log.txt).

Thank you!

**Comment by ammarik** [comment]
It seems to be solved, by using more powerful instance with more (4) cpu cores .
