### ISSUE TITLE
Unable to install deep learning Toolkit

### ISSUE THREAD

**Issue by CFDavidHou** [scipion-em/scipion-installer#28]
Hi there!

I would like to use deep learning tool to train particles picking but was unable to install the tool in the plugin manager. It always gives me the following errors, no mater how many times I have tried:

It stops when
```
00486:   Downloading pre-trained models...
```
Then in the Plugin.err:
```
00001:   /bin/sh: 1: update: not found
00002:   Exception in thread plugin-manager:
00003:   Traceback (most recent call last):
00004:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/threading.py", line 932, in _bootstrap_inner
00005:       self.run()
00006:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/threading.py", line 870, in run
00007:       self._target(*self._args, **self._kwargs)
00008:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/plugin_manager.py", line 769, in _applyOperations
00009:       self.reloadInstalledPlugin(op.getObjParent())
00010:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/plugin_manager.py", line 922, in reloadInstalledPlugin
00011:       self.tree.insert(pluginName, "end",
00012:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/plugin_manager.py", line 124, in insert
00013:       ttk.Treeview.insert(self, parent, index, iid, **kw)
00014:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/tkinter/ttk.py", line 1366, in insert
00015:       res = self.tk.call(self._w, "insert", parent, index,
00016:   _tkinter.TclError: Item deepLearningToolkit-0.2[scipion-em-xmipp] already exists
00017:   /bin/sh: 1: update: not found
00018:   Exception in Tkinter callback
00019:   Traceback (most recent call last):
00020:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
00021:       return self.func(*args)
00022:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/plugin_manager.py", line 685, in _deleteSelectedOperation
00023:       index = self.operationList.operationIndex(operation)
00024:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/plugin_manager.py", line 289, in operationIndex
00025:       if self.operationList[i].getObjName() == operation.getObjName():
00026:   AttributeError: 'NoneType' object has no attribute 'getObjName'
00027:   Exception in thread plugin-manager:
00028:   Traceback (most recent call last):
00029:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/threading.py", line 932, in _bootstrap_inner
00030:       self.run()
00031:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/threading.py", line 870, in run
00032:       self._target(*self._args, **self._kwargs)
00033:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/plugin_manager.py", line 769, in _applyOperations
00034:       self.reloadInstalledPlugin(op.getObjParent())
00035:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/plugin_manager.py", line 922, in reloadInstalledPlugin
00036:       self.tree.insert(pluginName, "end",
00037:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/site-packages/scipion/install/plugin_manager.py", line 124, in insert
00038:       ttk.Treeview.insert(self, parent, index, iid, **kw)
00039:     File "/opt/miniconda3/envs/.scipion3env/lib/python3.8/tkinter/ttk.py", line 1366, in insert
00040:       res = self.tk.call(self._w, "insert", parent, index,
00041:   _tkinter.TclError: Item deepLearningToolkit-0.2[scipion-em-xmipp] already exists
```
Any help and information would be great!

Thank you!

David

**Comment by dmaluenda** [comment]
Hi @CFDavidHou,

The most weird thing I read in the error log is the `/bin/sh: 1: update: not found`. However, I can't figure out why is triggered.

I imagine that you get the same when you run
```
cd SCIPION_HOME
./scipion3 installb deepLearningToolkit
```

Just to be sure. Can you past the result of the following command?
```
./scipion3 installb
```

Cheers,

**Comment by CFDavidHou** [comment]
Thank you @dmaluenda,

Command lines you suggested are WORKING!
I do:

scipion3 installb deepLearningToolkit

```
Downloading pre-trained models...
Regenerating local MANIFEST...
Verifying MD5s...
 14%...
...done. Updated files: 7
Uncompressing models: cat /opt/scipion/software/em/xmipp/models/xmipp_model_*.tgz | tar xzf - -i --directory=/opt/scipion/software/em/xmipp/models
 > Tensorflow installed with CUDA SUPPORT.
cd /opt/scipion/software/em/
Link 'deepLearningToolkit-0.2 -> deepLearningToolkit'
Created link: 'deepLearningToolkit-0.2 -> deepLearningToolkit'
Done (3 m 54 s)
```
And check with:

scipion3 installb

```
chimerax                 1.1     [X]     
deepLearningToolkit      0.2     [X]     
maxit                    10.1    [ ]     
motioncor2               1.2.6   [ ]     1.3.0   [ ]     1.3.1   [ ]     1.3.2   [ ]     1.4.0   [X]     
relion                   3.0     [ ]     3.1.0   [X]     
resmap                   1.95    [X]     
scipionchimera           1.0     [X]     
xmippSrc                 3.20.07 [X] 
```
Magic.

David

**Comment by azazellochg** [comment]
Looks like a bug in the plugin manager? @fonsecareyna82?
